SQLBackdoor/Models/ErrorViewModel.cs
using System;

namespace SQLBackdoor.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SQLBackdoor/Models/ExecutionResponse.cs
using System.Collections.Generic;
using System.Linq;

namespace SQLBackdoor.Models
{
    public class ExecutionResponse
    {
        public bool Error { get; set; }

        public string Message { get; set; }

        public IList<ExecutionResponseResult> Results { get; set; }

        public ExecutionResponse()
        {
            Results = new List<ExecutionResponseResult>();
        }
    }

    public class ExecutionResponseResult
    {
        public IEnumerable<ExecutionResponseResultColumn> Columns { get; set; }

        public IEnumerable<dynamic> Data { get; set; }

        public long Count => Data.Count();

        public ExecutionResponseResult()
        {
            Columns = new List<ExecutionResponseResultColumn>();
        }
    }

    public class ExecutionResponseResultColumn
    {
        public string Name { get; set; }

        public string Label { get; set; }
    }
}

SQLBackdoor/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using SQLBackdoor.Models;

using System.Diagnostics;

namespace SQLBackdoor.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SQLBackdoor/Controllers/SqlExecutorController.cs
using Dapper;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

using SQLBackdoor.Models;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Data.SqlClient;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace SQLBackdoor.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SqlExecutorController : ControllerBase
    {
        [HttpPost]
        public async Task<IActionResult> Post([FromForm] QueryData model)
        {

            try
            {
                var connectionString = $@"Data Source={model.Server};Initial Catalog={model.Database};User Id={model.Username};Password={model.Password};";

                if(model.File != null)
                {
                    using(var ms = new StreamReader(model.File.OpenReadStream()))
                    {
                        model.Query = ms.ReadToEnd();
                    }
                }

                if (!string.IsNullOrEmpty(model.Parameters))
                    connectionString += $"{model.Parameters}";

                var query = model.Query.Replace("&#039;", "'");

                using (var connection = new SqlConnection(connectionString))
                {
                    var ds = await connection.QueryMultipleAsync(query, commandTimeout: model.Timeout ?? 120);

                    //var ds = await connection.QueryAsync(query, commandTimeout: model.Timeout??120);

                    var response = new ExecutionResponse
                    {
                        Error = false,
                        Message = ""
                    };

                    IEnumerable<dynamic> result = null;
                    while(!ds.IsConsumed)
                    {
                        try
                        {
                            result = await ds.ReadAsync();
                            var (cols, data) = ReadColumns(result);
                            response.Results.Add(new ExecutionResponseResult
                            {
                                Columns = cols,
                                Data = data
                            });
                        }
                        catch (InvalidOperationException)
                        {
                            var data = ds.ReadFirstOrDefault();
                            response.Results.Add(new ExecutionResponseResult
                            {
                                Data = new List<dynamic>()
                            });
                        }                        
                    }                  
                        

                    return Ok(response);
                }
            }
            catch (SqlException ex)
            {
                return Ok(new ExecutionResponse { Error = true, Message = ex.Message });
            }
            catch (Exception ex)
            {
                return Problem(ex.Message);
            }
        }

        private (IEnumerable<ExecutionResponseResultColumn>,IEnumerable<dynamic>) ReadColumns(IEnumerable<dynamic> result)
        {
            if (!result.Any())
                return (new ExecutionResponseResultColumn[] { }, new dynamic[] { });

            var row = result.First();

            var dict = (IDictionary<string, object>)row;

            var cols = new List<ExecutionResponseResultColumn>();
            var data = new List<ExpandoObject>();
                        
            for(var i = 0; i < dict.Count; i++)
            {
                var key = dict.Keys.ElementAt(i);                
                var col = new ExecutionResponseResultColumn
                {
                    Name = $"column{i+1}",
                    Label = key
                };
                cols.Add(col);
            }

            var r = 1;
            foreach(var item in result)
            {
                var obj = (IDictionary<string, object>)item;                
                var expObj = new ExpandoObject();

                expObj.TryAdd("#", r);
                for(var i = 0; i < obj.Count; i++)
                {
                    var elem = obj.Values.ElementAt(i);
                    var colname = cols.ElementAt(i).Name;
                    expObj.TryAdd(colname, elem);
                }
                data.Add(expObj);
                r++;
            }

            cols.Insert(0,new ExecutionResponseResultColumn { Name = "#", Label = "#" });

            return (cols, data);
        }
    }

    public class QueryData
    {
        public IFormFile File { get; set; }
        public string Server { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Database { get; set; }
        public string Parameters { get; set; }
        public int? Timeout { get; set; }
        public string Query { get; set; }        
    }
}

SQLBackdoor/Views/Home/_Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="row no-gutters">
        <div class="col-12 col-md-3" id="sql-params-placement">
            <form class="px-2">
                <div class="form-group mb-2">
                    <label for="server">Connection Name</label>
                    <input type="text" class="form-control" id="connectionName">
                </div>
                <div class="form-group mb-2">
                    <label for="server">Server</label>
                    <input type="text" class="form-control" id="server">
                </div>
                <div class="form-group mb-2">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username">
                </div>
                <div class="form-group mb-2">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" placeholder="Password">
                </div>
                <div class="form-group mb-2">
                    <label for="database">Database</label>
                    <input type="text" class="form-control" id="database">
                </div>
                <div class="form-group mb-2">
                    <label for="parameters">Timeout</label>
                    <input type="text" class="form-control" id="timeout" placeholder="120">
                </div>
                <div class="form-group mb-2">
                    <label for="parameters">Parameters</label>
                    <input type="text" class="form-control" id="parameters">
                </div>
            </form>
        </div>
        <div class="col-12 col-md-9" id="sql-editor-placement">
            <partial name="_SQLEditor" />
        </div>
    </div>
</div>
<div class="container-fluid bg-light text-dark">
    <div id="data-result-placement">
        <table>
            <thead>
                <tr>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@section scripts{
    <script>
        var dtOpts = {
            autoWidth: false,
            ordering: false,
            searching: false,
            paging: false,
            info: false
        }

        var tabCharacter = "  ";
        var tabOffset = 2;
        var table = $("#data-result-placement table").DataTable(dtOpts);

        var urlSqlExecution = '@Url.Action("Post", "SqlExecutor")'

        $(document).ready(function () {
            hljs.initHighlightingOnLoad();
            hightlightSyntax();

            var connectionData = localStorage.getItem("lastConnection");
            var connectionString = JSON.parse(connectionData);

            if (connectionString != null) {
                $("#server").val(connectionString.Server);
                $("#username").val(connectionString.Username);
                $("#password").val(connectionString.Password);
                $("#database").val(connectionString.Database);
                $("#parameters").val(connectionString.Parameters);
                $("#timeout").val(connectionString.Timeout);
            }
         
            $(document).on('click', '#indent', function (e) {
                e.preventDefault();
                var self = $(this);

                self.toggleClass('active');

                if (self.hasClass('active')) {
                    tabCharacter = "\t";
                    tabOffset = 1;
                }
                else {
                    tabCharacter = "  ";
                    tabOffset = 2;
                }
            })

            $(document).on('click', '#fullscreen', function (e) {
                e.preventDefault();
                var self = $(this);

                self.toggleClass('active');
                self.parents('.editor-holder').toggleClass('fullscreen');
            });

            $(document).on('click', '#btn-execute', function (e) {

                var me = $('.editor');
                var content = me.val();

                if (content == "" || content == undefined) {
                    alert("Erro de sintaxe!");
                    e.preventDefault();
                    return;
                }

                var request = {
                    "Server": $("#server").val(),
                    "Username": $("#username").val(),
                    "Password": $("#password").val(),
                    "Database": $("#database").val(),
                    "Parameters": $("#parameters").val(),
                    "Timeout": $("#timeout").val(),
                    "Query": content
                };

                localStorage.setItem($("#connectionName").val(), JSON.stringify(request));
                localStorage.setItem("lastConnection", JSON.stringify(request));

                $.post(
                    {
                        url: urlSqlExecution,
                        contentType: "application/json",
                        dataType: 'json',
                        data: JSON.stringify(request),
                        beforeSend: function () {
                            $("#data-result-placement").hide();
                        },
                        success: function (data) {
                            console.log(data);
                            if (data.error) {
                                alert(data.message);
                                return;
                            }

                            populateDataTable(data);
                        },
                        error: function (e,x,h,t) {
                            console.log("There was an error with your request...");
                            console.log("error: " + JSON.stringify(e));
                            alert("Erro não esperado");
                        }
                    });

                e.preventDefault();
            });

            /*------------Url-----------------------------
            Capture text updates
            ------------------------------------------*/
            $(document).on('ready load keyup keydown change', '.editor', function () {
                correctTextareaHeight(this);
                hightlightSyntax();
            });


            /*------------------------------------------
            Enable tabs in textarea
            ------------------------------------------*/
            $(document).delegate('.allow-tabs', 'keydown', function (e) {
                var keyCode = e.keyCode || e.which;

                if (keyCode == 9) {
                    e.preventDefault();
                    var start = $(this).get(0).selectionStart;
                    var end = $(this).get(0).selectionEnd;

                    // set textarea value to: text before caret + tab + text after caret
                    $(this).val($(this).val().substring(0, start)
                        + tabCharacter
                        + $(this).val().substring(end));

                    // put caret at right position again
                    $(this).get(0).selectionStart =
                        $(this).get(0).selectionEnd = start + tabOffset;
                }
            });
        });

        /*------------------------------------------
            Resize textarea based on content
        ------------------------------------------*/
        function correctTextareaHeight(element) {
            var self = $(element),
                outerHeight = self.outerHeight(),
                innerHeight = self.prop('scrollHeight'),
                borderTop = parseFloat(self.css("borderTopWidth")),
                borderBottom = parseFloat(self.css("borderBottomWidth")),
                combinedScrollHeight = innerHeight + borderTop + borderBottom;

            if (outerHeight < combinedScrollHeight) {
                self.height(combinedScrollHeight);
            }
        }


        /*------------------------------------------
            Run syntax hightlighter
        ------------------------------------------*/
        function hightlightSyntax() {
            var me = $('.editor');
            var content = me.val();
            var codeHolder = $('code');
            var escaped = escapeHtml(content);

            codeHolder.html(escaped);

            $('.syntax-highight').each(function (i, block) {
                hljs.highlightBlock(block);
            });
        }


        /*------------------------------------------
            String html characters
        ------------------------------------------*/
        function escapeHtml(unsafe) {
            return unsafe
                .replace(/&/g, "&amp;")
                .replace(/</g, "&lt;")
                .replace(/>/g, "&gt;")
                .replace(/"/g, "&quot;")
                .replace(/'/g, "&#039;");
        }

        function populateDataTable(response) {
            
            if (response == null
                || response == undefined
                || response.data.length <= 0) return;

            if (table) {
                table.destroy();
                $("#data-result-placement table").empty()
            }

            var columns = [];
            var columnNames = Object.getOwnPropertyNames(response.data[0]);

            for (var i = 0; i < columnNames.length; i++) {
                columns.push({
                    title: columnNames[i],
                    data: columnNames[i],
                    render: function (data, type, row, meta) {
                        return type === 'display' && data === null
                            ? 'NULL'
                            : data
                    }
                })
            }

            dtOpts.data = response.data
            dtOpts.columns = columns;
            table = $("#data-result-placement table").DataTable(dtOpts);
            table.draw();

            $("#data-result-placement").show();
        }
    </script>
}

SQLBackdoor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SQLBackdoor</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/styles/dracula.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/darkly/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css" />
    @*<link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css" />*@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pace-js@latest/pace-theme-default.min.css">
    <link href="~/css/bounce.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @RenderBody()

    <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://use.fontawesome.com/b2c0f76220.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/highlight.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/languages/sql.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>
    <script data-pace-options='{ "ajax": true }' src="https://cdn.jsdelivr.net/npm/pace-js@latest/pace.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SQLBackdoor/Views/Shared/_SQLEditor.cshtml
<div class="editor-holder">
    <ul class="toolbar">
        @*<li><a href="#" id="indent" title="Toggle tabs or spaces"><i class="fa fa-indent"></i></a></li>
        <li><a href="#" id="fullscreen" title="Toggle fullscreen mode"><i class="fa fa-expand"></i></a></li>*@
        <li><a href="#" id="btn-execute" title=""><i class="fa fa-play"></i></a></li>
    </ul>
    <div class="scroller">
        <textarea class="editor allow-tabs" spellcheck="false"></textarea>
        <pre><code class="syntax-highight sql"></code></pre>
    </div>
</div>